server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      routes:
        # 🔹 RUTA - Microservicio de estudiantes
        - id: student
          uri: lb://microservice-student
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=1

        # 🔹 RUTA - Microservicio de cursos
        - id: curso
          uri: lb://microservice-curso
          predicates:
            - Path=/api/cursos/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
