server:
  port: 8090

spring:
  application:
    name: microservice-student
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentDb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: julio1
  jpa:
    hibernate:
      ddl-auto: update   #  usa 'update' para mantener datos entre reinicios
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
